name: Generate random plot

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.5'

      - name: Install ggplot2 (with R deps only)
        run: |
          Rscript -e 'install.packages("ggplot2", repos="https://cloud.r-project.org")'
      - name: Configure Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Commit and push plot
        run: |
          git add plot.png
          git commit -m "Update plot" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:main
